//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiONG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int cod_com { get; set; }
        public string comen { get; set; }
        public int cod_den { get; set; }
        public int cod_usu { get; set; }
    
        public virtual Denuncia Denuncia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
