//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiONG
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonacionProducto
    {
        public int cod_donpro { get; set; }
        public int cod_don { get; set; }
        public int cod_pro { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Donaciones Donaciones { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
