//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiONG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto_Mascota
    {
        public int cod_foto_mas { get; set; }
        public string foto { get; set; }
        public int cod_mas { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
