//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiONG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like_Comentario
    {
        public int cod_like { get; set; }
        public Nullable<bool> liked { get; set; }
        public int cod_com { get; set; }
    
        public virtual Comentario Comentario { get; set; }
    }
}
